### ISSUE TITLE
[1337x] Exception (1337x): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: Maximum timeout reached. maxTimeout=55000 (ms): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: Maximum timeout reached. maxTimeout=55000 (ms) (Test)

### ISSUE THREAD

**Issue by NasKar2** [FlareSolverr/FlareSolverr#284]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**:2.1.0
* **Last working FlareSolverr version**:2.1.0
* **Operating system**:TrueNAS 12.2 U5.1
* **Are you using Docker**: [yes/no]no
* **FlareSolverr User-Agent (see log traces or / endpoint)**:?
* **Are you using a proxy or VPN?** [yes/no]no
* **Are you using Captcha Solver:** [yes/no]no
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Description
1337x was working and now has stopped.  service flaresolverr status shows it's running. I restart the jails for jackett and flaresolverr without help. 
netstat -an | grep 8191
tcp4       0      0 192.168.5.86.8191      *.*                    LISTEN

[List steps to reproduce the error and details on what happens and what you expected to happen]
click on test on the 1337x button in jackett
### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]
Exception (1337x): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: Maximum timeout reached. maxTimeout=55000 (ms): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: Maximum timeout reached. maxTimeout=55000 (ms)
[Make sure you attach the full logs with your personal information removed in case we need more information]
Can't find the logs. Help with that would be great. I looked at the wiki and don't know how to set the environment variables.
### Screenshots
![image](https://user-images.githubusercontent.com/31674727/151665550-7ccfedbe-7fbf-4912-9ff6-f8d1cef2fccf.png)

[Place any screenshots of the issue here if needed]

**Comment by nafeasonto** [comment]
I am getting this also, are you running a VPN?

**Comment by NasKar2** [comment]
Not in the flaresolverr or jackett jails

**Comment by ilike2burnthing** [comment]
Try freeing up resources to see if that helps, otherwise try increasing the timeout in Jackett (e.g. 90000).

**Comment by NasKar2** [comment]
Changing to timeout of 90000 just delays the error.  Have 64 GIGs of memory so I don't think that is the problem

**Comment by ilike2burnthing** [comment]
Which URL are you using 1337x? Are you able to access this URL in browser from the same IP, using the same DNS? Have you tried using a different URL?

**Comment by vermiboy** [comment]
Same error here ver.2.1.0 on windows

**Comment by nafeasonto** [comment]
This happens to me if my VPN is up and I attempt to even run Flaresolverr.  I have to take down the VPn, run Flaresolverr, it connects, then put my VPN back up.  It's weird.

**Comment by vermiboy** [comment]
i don't have any vpn up :(

**Comment by ngosang** [comment]
FlareSolverr 2.2.0 is released. I'm not sure if it will fix this issue but it includes relevant changes.

**Comment by NasKar2** [comment]
Using https://1337x.to/
Upgrade to 2.2 with a git pull and service restart and same error

**Comment by NasKar2** [comment]
After checking the ip:port it appears that the version didn’t change. Trying to install from scratch caused errors see https://gist.github.com/Zamana/68060da614909ed3531acbda6154f67d

**Comment by ilike2burnthing** [comment]
@Zamana any issues for you updating to v2.2.0?

Any TrueNAS jail related reason you can think of which would cause FlareSolverr to seemingly just hang indefinitely?

**Comment by ngosang** [comment]
@NasKar2 Run `npm install`
@Zamana you are using NodeJS 14 in your instructions but I'm testing with NodeJS 16. Could you check if NodeJS 16 is available in the FreeBSD repository?

**Comment by Zamana** [comment]
Hi!

After updating to 2.2.0, I'm unable to build:

```root@flaresolverr:/usr/local/share/FlareSolverr # npm run build

> flaresolverr@2.2.0 build /usr/local/share/FlareSolverr
> tsc

src/providers/cloudflare.ts:1:15 - error TS2305: Module '"puppeteer"' has no exported member 'HTTPResponse'.

1 import {Page, HTTPResponse} from 'puppeteer'
                ~~~~~~~~~~~~

src/services/solver.ts:1:15 - error TS2305: Module '"puppeteer"' has no exported member 'HTTPResponse'.

1 import {Page, HTTPResponse} from 'puppeteer'
                ~~~~~~~~~~~~


Found 2 errors.
```

Node version is v14.18.1

**Comment by ngosang** [comment]
@Zamana Install Node16 and run `npm install`

**Comment by Zamana** [comment]
Exactly same error (error TS2305: Module '"puppeteer"' has no exported member 'HTTPResponse'.) after installing node16.

**Comment by ngosang** [comment]
That error is not caused by Node, it's because you have an old version of "puppeteer" in "node_modules" folder.
1) Remove the folder "node_modules"
2) Remove the folder "dist"
3) Execute "npm install"
4) Execute "npm start"

**Comment by Zamana** [comment]
Same error...

**Comment by wklink** [comment]
I've been getting the same error since flaresolver upgraded to 2.2.0.  Downgrading flaresolver to 2.1.0 and it works fine for me.

**Comment by NasKar2** [comment]
Does 1337x work?  If so wahat are your settings for it.

**Comment by ngosang** [comment]
You can try FlareSolverr v2.2.1

**Comment by Zamana** [comment]
Any chance to fix this incompatibility of 2.2.0 with FreeBSD?

**Comment by Zamana** [comment]
Version 2.2.1 doesn't work either:

Output of ```npm run build``` (using nodeJS16):

```
> flaresolverr@2.2.1 build /usr/local/share/FlareSolverr
> tsc

src/providers/cloudflare.ts:1:34 - error TS7016: Could not find a declaration file for module 'puppeteer'. '/usr/local/share/FlareSolverr/node_modules/puppeteer/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/puppeteer` if it exists or add a new declaration (.d.ts) file containing `declare module 'puppeteer';`

1 import {Page, HTTPResponse} from 'puppeteer'
                                   ~~~~~~~~~~~

src/providers/cloudflare.ts:63:53 - error TS7006: Parameter 'selector' implicitly has an 'any' type.

63           const displayStyle = await page.evaluate((selector) => {
                                                       ~~~~~~~~

src/services/sessions.ts:3:23 - error TS7016: Could not find a declaration file for module 'puppeteer'. '/usr/local/share/FlareSolverr/node_modules/puppeteer/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/puppeteer` if it exists or add a new declaration (.d.ts) file containing `declare module 'puppeteer';`

3 import {Browser} from 'puppeteer'
                        ~~~~~~~~~~~

src/services/solver.ts:1:34 - error TS7016: Could not find a declaration file for module 'puppeteer'. '/usr/local/share/FlareSolverr/node_modules/puppeteer/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/puppeteer` if it exists or add a new declaration (.d.ts) file containing `declare module 'puppeteer';`

1 import {Page, HTTPResponse} from 'puppeteer'
                                   ~~~~~~~~~~~


Found 4 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! flaresolverr@2.2.1 build: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the flaresolverr@2.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-06T16_52_19_659Z-debug.log
```

**Comment by ngosang** [comment]
I'm pretty sure you are not installing FlareSolverr correctly.
In the folder `/usr/local/share/FlareSolverr/node_modules/puppeteer/` you will find a file called `package.json`
Check the package version in that file. It must be `13.1.2` as defined in FlareSolverr `package.json`. If it's not, you have to remove the folder `/usr/local/share/FlareSolverr/node_modules` and start from scratch. Make sure the FlareSolverr `package.json` is the same as in the master branch of this Git repository.

**Comment by rglover666** [comment]
I was able to get all of the latest running in TrueNAS jail by hacking puppeteer's launcher.js to use chrome (it was ignoring the environment variables) but FlareSolverr still spins forever and times out.  Here is my debug log:

[FlareSolverr.log](https://github.com/FlareSolverr/FlareSolverr/files/8048650/FlareSolverr.log)

I set the timeout to 20 seconds to limit the size of the log but it behaves the same regardless of the timeout setting

I installed the Windows version and am using that for the time being, but I would like to see this fixed for FreeBSD.

**Comment by ngosang** [comment]
FlareSolverr v2.2.3
